### ISSUE TITLE
Bounding boxes can be created and moved outside of the image

### ISSUE THREAD

**Issue by quicklizard99** [NaturalHistoryMuseum/inselect#117]
It is possible to drag-drop, resize and create bounding boxes that are either completely or partially outside of the image.

If any of the bounding boxes are outside the image, inselect produces an ugly error messages when the document is saved and when cropped specimen images are saved.

**Comment by llivermore** [comment]
The segment algorithm can create bounding boxes outside of the image. Tested using "largest slides.jpg" in Inselect 0.1.6

**Comment by quicklizard99** [comment]
The segmentation algorithm has been seen (by @llivermore ) to create boxes that are partially outside of the image.

Inselect now permits boxes to be partially or entirely outside of the image. The saved cropped specimen images contain black in areas that are not within the image.
