### ISSUE TITLE
"Close" doesn't clean up properly

### ISSUE THREAD

**Issue by jholetschek** [NaturalHistoryMuseum/inselect#123]
Apparently, "close" doesn't reset the application completely. After a fresh start, I can segment an image successfully. I can then close and open another image (with "new"), but segmenting an image doesn't work, no segments/metadata entries are created. After restarting Inselect, this works fine.
(on Win7Prof SP1 64bit)

**Comment by quicklizard99** [comment]
I have been unable to recreate this problem. The relevant parts of Inselect have been rewritten since this bug was reported.
