### ISSUE TITLE
"New" doesn't work if inselect document already exists.

### ISSUE THREAD

**Issue by jholetschek** [NaturalHistoryMuseum/inselect#124]
Opening an image with "New..." doesn't work if it has been opened before, that is an .inselect file already exists. (on Win7Prof SP1 64bit)

**Comment by quicklizard99** [comment]
Related to #104 and #108.

Suggest that File, New is removed and the behaviour of File, Open is altered as follows
* File filter to accept .inselect file extension and all supported image file extensions
* User selects a .inselect file
    * Open the .inselect file
* User selects an image file for which a .inselect document already exists
    * Open the .inselect file
* User selects  a _thumbnail.jpg file corresponding to an existing .inselect file
    * Open the .inselect file
* User selects  an image file
    * Create and open a new .inselect file
