### ISSUE TITLE
Barcode reading broken in compiled Inselect on Windows

### ISSUE THREAD

**Issue by quicklizard99** [NaturalHistoryMuseum/inselect#130]
Install Inselect 0.1.6. Press the 'Read barcodes' buttons and you see an ugly error message: 'An error occurred: {A34FC1A7-C73F-4706-886E-C4A33E37C6E5}'.

**Comment by quicklizard99** [comment]
The 'Read barcodes' button works fine when Inselect is run from source. The problem lies with our installer - cx_Freeze - which misses out some Python files. The [bug report](https://bitbucket.org/anthony_tuininga/cx_freeze/issue/44/win32com-relies-on-modules-with-non) about this has been open for some time.

A workaround is for the user to copy a file into Inselect's installation directory. Contact me for the file and instructions.

**Comment by llivermore** [comment]
I've followed the instructions in the email you sent and I'm running 32bit Windows 7.

I get the following error when I try to segment "An error occurred: One or more boxes are not normalised".

**Comment by llivermore** [comment]
If testing on Windows you must run the Inlite Control Centre once before the "read barcodes" functionality works correctly.

**Comment by quicklizard99** [comment]
v0.1.8 (f8f0667) introduces support for the open-source `libdmtx` decoder on all platforms. See
[NaturalHistoryMuseum/libdmtx](/NaturalHistoryMuseum/libdmtx/) and [NaturalHistoryMuseum/dmtx-wrappers](/NaturalHistoryMuseum/dmtx-wrappers/)

**Comment by quicklizard99** [comment]
Fixed by a0feac2
