### ISSUE TITLE
Avoiding crop file name collisions

### ISSUE THREAD

**Issue by bwprice** [NaturalHistoryMuseum/inselect#155]
When cropping images file names may be duplicated if for example the same taxon and drawer and the barcode has not been read.

Resulting filename is [missing barcode]_xxxxx_yyyy.jpg

Program mentions "duplicate file name" on export, but not clear this will only result in one crop saved, ie other crop overwritten..

potential solution:
allow saving crops but prevent duplicate file names by appending a suffix if duplicated detected...

inselect 0.1.10, windows 64bit, 4GB RAM, scan # 28b

**Comment by quicklizard99** [comment]
Closed by 734ec5e
