### ISSUE TITLE
Code coverage report

### ISSUE THREAD

**Issue by quicklizard99** [NaturalHistoryMuseum/inselect#158]
Inselect's build script produces a code coverage report (using Python's [coverage module](https://pypi.python.org/pypi/coverage)). Make this more visible via [Coveralls](https://coveralls.io/).

**Comment by quicklizard99** [comment]
To do this we must grant access Coveralls access to the Inselect github repo.

Coveralls requests access to all organisational repos of which the github user is a member - it does not seem to be possible to grant access to just one organisation's repository. This is a potential sticking point because I am a member of UNEP-WCMC, which has some private github repos.

**Comment by stefanv** [comment]
Would you like me to generate a token?

**Comment by stefanv** [comment]
I've enabled coveralls for the inselect repo.

**Comment by quicklizard99** [comment]
Fantastic! Inselect is now showing on [coveralls](https://coveralls.io/r/NaturalHistoryMuseum/inselect) Thanks @stefanv.
