### ISSUE TITLE
default segmentation pattern

### ISSUE THREAD

**Issue by bwprice** [NaturalHistoryMuseum/inselect#192]
When using standard templates (eg 100 slide templates) it is much faster and more accurate to use a template which has already been segmented and cleaned and use the copy function. A default "slide 100" segmentation pattern or similar would streamline this activity.

**Comment by quicklizard99** [comment]
Good idea - this might best be done by being part of an Inselect template file.

**Comment by bwprice** [comment]
agreed, makes sense as an optional part of a template. Future "slide template" based imaging could then have ingest, segmentation, barcode reading and image cropping out completely automated.

**Comment by quicklizard99** [comment]
Yes, that would be really good. Perhaps a new command 'Save to new template', which prompts the user for the name of a new `.inselect_template` file and saves the currently loaded template + current items. Save just the bounding boxes or also include metadata?

Inselect would add the default bounding boxes (and possibly metadata) when a new file is ingested. We would also need to change the `ingest` command-line tool to take an optional path to a `.inselect_template` file.

**Comment by quicklizard99** [comment]
After discussion with the group 2016-03-04, we will have 'Bounding box' / 'Segmentation' / 'Cookie cutter' templates (separate to metadata templates; name to be decided) that specify the locations of bounding boxes. These boxes can be created either when images are ingested or/and as a separate manual step.

**Comment by quicklizard99** [comment]
A couple of concerns
* @benscott feels we should have a more automated method that combines the results of segmentation with the refined boxes previously saved by the user
* Drift in precise location of template within images might cause cookie cutter-produced bounding boxes to not align on top of objects - @quicklizard to investigate this
