### ISSUE TITLE
Help for hotkeys

### ISSUE THREAD

**Issue by quicklizard99** [NaturalHistoryMuseum/inselect#207]
* Keyboard + mouse picture highlighting behaviour
* Show on startup - checkbox to not show next time
* Available under Help

@llivermore has some ideas about how this will look.

**Comment by quicklizard99** [comment]
Possiblities

* http://i.stack.imgur.com/sX8yo.png
* http://media02.hongkiat.com/cheatsheet-graphic-designers/photoshop-shortcuts.jpg
* http://hydra-media.cursecdn.com/mwo.gamepedia.com/5/5f/Keylayout.jpg
* https://s-media-cache-ak0.pinimg.com/736x/41/52/e8/4152e816d965e0ecdf3b92b07a914936.jpg

**Comment by quicklizard99** [comment]
github shows hotkeys when the user presses `?`:

![image](https://cloud.githubusercontent.com/assets/1640027/13547199/f0385f98-e2bf-11e5-86c7-3effe2e1c34f.png)

**Comment by quicklizard99** [comment]
Of all the ways of presenting keyboard shortcuts that I have seen, I think this is the clearest

![image](https://cloud.githubusercontent.com/assets/1640027/14640830/4ba44d94-063b-11e6-973a-de70db26c985.png)

**Comment by llivermore** [comment]
Agreed, that's clean and elegant. Getting the transparency right seems like the hardest part there!
