### ISSUE TITLE
increase default border around "objects" post segmentation

### ISSUE THREAD

**Issue by bwprice** [NaturalHistoryMuseum/inselect#213]
Bounding boxes are 1 or 2 pixels away from the actual edge, this needs to be increased to ~10 pixels to give the cropped image better context. This would be better implemented automatically as part of the segmentation process, rather than as a post-segmentation "grow boxes" or similar.

**Comment by quicklizard99** [comment]
No padding
![ephemeroptera-no-padding](https://cloud.githubusercontent.com/assets/1640027/14521378/ed2b1f2c-0220-11e6-966b-5a3d2f3bdc4e.jpg)

Padding of 1% of height and width
![ephemeroptera-1](https://cloud.githubusercontent.com/assets/1640027/14521329/b5eb3e2a-0220-11e6-888c-f355ae0f479a.jpg)


No padding
![scopelodes-no-padding](https://cloud.githubusercontent.com/assets/1640027/14521332/b5fb1d36-0220-11e6-8c71-79a36521cb0d.jpg)

Padding of 1% of height and width
![scopelodes-1](https://cloud.githubusercontent.com/assets/1640027/14521331/b5f79b52-0220-11e6-95e8-49f8529d0c04.jpg)


No padding
![slide-no-padding](https://cloud.githubusercontent.com/assets/1640027/14521334/b600f850-0220-11e6-8362-0d900321843f.jpg)

Padding of 1% of height and width
![slide-1](https://cloud.githubusercontent.com/assets/1640027/14521333/b5fcbb32-0220-11e6-8201-ecc38029d134.jpg)


No padding
![diptera-no-padding](https://cloud.githubusercontent.com/assets/1640027/14521538/a25aa5ca-0221-11e6-9437-00ce39041f53.jpg)

Padding of 1% of height and width
![diptera-1](https://cloud.githubusercontent.com/assets/1640027/14521537/a256e2d2-0221-11e6-8bbf-8bb6b9d39958.jpg)

**Comment by llivermore** [comment]
That looks pretty good to me. Can you expose padding in a setting?

**Comment by quicklizard99** [comment]
Thanks @llivermore. I would rather not ask the user to fiddle around with values unless this is absolutely necessary.
