### ISSUE TITLE
An Error Occurred: {'Choices with data ...

### ISSUE THREAD

**Issue by FetznerJ** [NaturalHistoryMuseum/inselect#254]

**Comment by quicklizard99** [comment]
I have edited the issue so that the traceback and the YAML template are wrapped in a 'fence' - three backticks (\`\`\`) at the start and end of each block

**Comment by quicklizard99** [comment]
The template specifies that the `Order` and `Family` fields are `Choices with data` (lines 41 and 46) but these contains lists rather than mappings. If you want to show a drop-down list of options, change 41 and 46 to `Choices`. If you want to associate values with the displayed list of options then change the contents of the `Choices with data` blocks to be mappings e.g.,
```
      Choices with data:
            Ancistropsyllidae: 1
            Ceratophyllidae: 2
            Chimaeropsyllidae: 3
```

The error message from Inselect is cryptic. We will fix this.

**Comment by FetznerJ** [comment]
Ok, that makes sense. That for the information.

I appreciate you guys creating and maintaining this software. It will be immensely useful to the digitization community.

Cheers,
Jim

Sent from my iPhone

On Apr 6, 2016, at 1:24 PM, Lawrence Hudson <notifications@github.com<mailto:notifications@github.com>> wrote:


The template specifies that the Order and Family fields are Choices with data (lines 41 and 46) but these contains lists rather than mappings. If you want to show a drop-down list of options, change 41 and 46 to Choices. If you want to associate values with the displayed list of options then change the contents of the Choices with data blocks to be mappings e.g.,

      Choices with data:
            Ancistropsyllidae: 1
            Ceratophyllidae: 2
            Chimaeropsyllidae: 3


The error message from Inselect is cryptic. We will fix this.

-
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/NaturalHistoryMuseum/inselect/issues/254#issuecomment-206474692>



The information contained in this message and/or attachments is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any system and destroy any copies. Any views expressed in this message are those of the individual sender.

**Comment by quicklizard99** [comment]
Great, thanks Jim - please let us know if you hit any more problems.
