### ISSUE TITLE
Mac OS X installer bloat

### ISSUE THREAD

**Issue by quicklizard99** [NaturalHistoryMuseum/inselect#292]
In order to implement #212 we made use of the `scipy` and `sklearn` libraries, which have increased the size of the Mac OS X installer from 122 MB to 262 MB. The Windows installers were not badly affected but we would like to keep things as lean as possible.

Some options
- Can we include only those bits of `scipy` and `sklearn` that we are actually using?
- Can we reduce the size of the `.dmg` installer?

**Comment by stefanv** [comment]
One option would be to reduce the dependencies, either by using KDE from scipy (see https://jakevdp.github.io/blog/2013/12/01/kernel-density-estimation/) or by including the KDE from scikit-learn.  Also, the relative minimum finder used in #212 is pure Python so can easily be copied over (there's no problem with the license, as long as the LICENSE file comes along and is mentioned in the Inselect license).

**Comment by quicklizard99** [comment]
Thanks @stefanv - very useful. I will have a look at including relevant source and attributing it.

**Comment by quicklizard99** [comment]
Splitting out relevant bits of scipy and sklearn turns out to be very tricky. It is easy enough for the  'minima detection' bit but harder for kernel density estimation.

**Comment by quicklizard99** [comment]
Most of the bloat results from `PyInstaller`'s approach of creating a copy of the relevant bits of the virtual env for each frozen binary. We have six binaries - the Inselect application itself and five command-line tools: `export_metadata`, `ingest`, `read_barcodes`, `save_crops` and `segment`. So any large binaries could be duplicated up to six times. `OpenCV` will be present in 
five of the six binaries. Contrast this with the approach of `cx_Freeze`, which creates a single copy of the virtual env that is shared among the six binaries. We use `cx_Freeze` to create the Windows installers - I was unable to get a working Mac OS X build using `cx_Freeze`.

Given that most folks won't be interested in the command line tools, I have altered `build.sh` to create two installers - one containing the Inselect application and one containing the five command-line tools.
