### ISSUE TITLE
Download boxes indicate Mac/PC

### ISSUE THREAD

**Issue by JadeLaurenCawthray** [NaturalHistoryMuseum/inselect#310]

**Comment by JadeLaurenCawthray** [comment]
Unless you speak computer language its not clear at https://naturalhistorymuseum.github.io/inselect/ which set of files to download.  We should explicitly label these as Mac or PC

**Comment by quicklizard99** [comment]
The install page (https://naturalhistorymuseum.github.io/inselect/pages/install.html) updated to indicate Mac vs PC.
