### ISSUE TITLE
Change URL?

### ISSUE THREAD

**Issue by JadeLaurenCawthray** [NaturalHistoryMuseum/inselect#311]
Is it possible to change the URL to something more memorable?

**Comment by quicklizard99** [comment]
The URL - https://naturalhistorymuseum.github.io/inselect/ - is assigned by github and we cannot change it. We could register our own domain name (inselect.org? inselect.eu?) and serve content from github pages (https://help.github.com/articles/using-a-custom-domain-with-github-pages/)
