### ISSUE TITLE
Error 5

### ISSUE THREAD

**Issue by JessUtrup** [NaturalHistoryMuseum/inselect#353]
We've been having trouble when we try to save crops. An "Error #5" message pops up. We try repeatedly to save, and eventually it does, but we were hoping to learn how to avoid this error.

**Comment by quicklizard99** [comment]
Hi @JessUtrup. Sorry that you have had this problem - we have not seen it before.

1. Are using the latest release of Inselect (v0.1.33)?

2. What operating system are you using?

3. The popup box should have a button labelled 'Copy details' - could you press this button the next time the error occurs and paste the details into a new comment on this page?

**Comment by JessUtrup** [comment]
1. Yes, we are using v0.1.33.
2. Both computers on which we have Inselect (and both get this error) run on Windows 7.
3. We could not find a 'Copy Details' button, so I've emailed a screenshot of the error to you directly.

**Comment by quicklizard99** [comment]
Screenshot

![image](https://cloud.githubusercontent.com/assets/1640027/18554494/5dae50b6-7b5c-11e6-9899-7b6aeb5c6a03.png)

**Comment by quicklizard99** [comment]
Thanks @JessUtrup. This error has been seen when saving crops to a Dropbox folder (#332). Are you running Dropbox on these PCs? If so, could you pause Dropbox syncing and export crops again?

**Comment by JessUtrup** [comment]
Dropbox isn't installed on either computer, and none of the internet browsers have a Dropbox account logged in.

**Comment by quicklizard99** [comment]
Thanks @JessUtrup. Very interesting. There is a program running on these PCs that is examining new directories and/or files and is interfering with Inselect's export crops function. We need to find and pause whatever program this. It could be a program that is similar to Dropbox - something like Google Drive, Box or SugarSync. Could you look for any of these programs, pause them and export crops again?

It could also be a virus scanner - this might be called Norton, Symantec, Kaspersky or Sophos. If you have a virus scanner running, could you also try pausing it and running export crops?

The long-term solution is for us to alter Inselect to export crops in a way that is tolerant of these sorts of virus scanner and programs like Dropbox.

**Comment by JessUtrup** [comment]
It seems to be some managed software from our institution that might be causing the problem (IBM BigFix). If we pause that, we can save the crops. Or if we just keep trying to save the crops, we'll stumble upon the moment when that isn't running and it will save them successfully.

**Comment by quicklizard99** [comment]
Great - very glad that you have identified the software and have a work-around.

I have closed this issue now because I have altered Inselect to tolerate these other applications. I will let you know when we the next release of Inselect is available.

**Comment by JessUtrup** [comment]
Thank you!
