### ISSUE TITLE
Missing file to download at /inselect/pages/documentation.html

### ISSUE THREAD

**Issue by pierreneter** [NaturalHistoryMuseum/inselect#440]
https://naturalhistorymuseum.github.io/inselect/pages/documentation.html
This URL: https://www.dropbox.com/s/dwdtrrxxfoul9fo/InselectDocumentationFiles.zip?dl=0 return 404
Please check, thank you so much. I feel very eager with this software, feel very motivated

**Comment by llivermore** [comment]
Hi pierreneter, we will try and restore the tutorial files but this will probably be after the Christmas holidays.

Best wishes,
Laurence

**Comment by quicklizard99** [comment]
Now fixed. Apologies for the delay in restoring this archive.

**Comment by pierreneter** [comment]
Thank you so much!
